import asyncio
from openai import AsyncOpenAI
from src.context_extractor import ProjectContext
from src.agent_builder import build_agent_prompts, AGENTS


SYSTEM_PROMPT = """You are an expert AI CTO system prompt generator. Given context about a software project, you generate highly specific, project-aware system prompts for 8 specialized AI CTO agents.

The 8 agents are:
1. cto_orchestrator - Coordinates all agents, manages pipeline
2. cto_audit_analyzer - Parses audits, security, performance findings
3. cto_architect - Designs and reviews system architecture, APIs
4. cto_planner - Creates implementation plans, breaks down tasks
5. cto_executor - Generates code, implements features, fixes bugs
6. cto_tester - Writes tests, reviews code quality, analyzes test results
7. cto_monitor - Tracks progress, identifies bottlenecks, status reports
8. cto_documenter - Generates READMEs, API docs, architecture docs, code comments

Each prompt should be:
- Specific to this project's tech stack, structure, and conventions
- Actionable with clear role definition
- Reference actual file paths, tools, and patterns found in the project
- Include coding standards, testing conventions, and deployment practices
- Keep it concise but comprehensive (200-400 words per agent)

Return ONLY valid JSON with keys matching the agent names."""


async def generate_with_llm(
    context: ProjectContext,
    api_key: str,
    base_url: str,
    model: str,
) -> dict[str, str]:
    client = AsyncOpenAI(api_key=api_key, base_url=base_url)

    user_prompt = f"""Generate AI CTO agent prompts for this project:

{context.raw_context}

Return a JSON object with exactly these keys:
{", ".join(AGENTS)}

Each value should be the full system prompt for that agent, tailored to this specific project.

IMPORTANT: Return ONLY valid JSON. No markdown, no explanation, no code blocks."""

    try:
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=4096,
        )

        content = response.choices[0].message.content or "{}"

        # Strip markdown code blocks if present
        content = content.strip()
        if content.startswith("```"):
            lines = content.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            content = "\n".join(lines)

        import json
        result = json.loads(content)

        for agent in AGENTS:
            if agent not in result:
                result[agent] = ""

        await client.close()
        return result

    except Exception as e:
        await client.close()
        raise RuntimeError(f"LLM generation failed: {e}")


async def generate_hybrid(
    context: ProjectContext,
    api_key: str,
    base_url: str,
    model: str,
) -> dict[str, str]:
    template_prompts = build_agent_prompts(context)

    client = AsyncOpenAI(api_key=api_key, base_url=base_url)

    agent_list = "\n".join(
        f"- {agent}: {template_prompts[agent][:100]}..." for agent in AGENTS
    )

    user_prompt = f"""You are refining AI CTO agent prompts for this project.

PROJECT CONTEXT:
{context.raw_context}

CURRENT TEMPLATE PROMPTS (generated by scanner):
{agent_list}

Your job: Improve these prompts by:
1. Adding deeper insights from the project context
2. Making them more specific to this project's actual code patterns
3. Adding language-specific best practices
4. Including framework-specific conventions
5. Making the prompts more actionable and precise

Return ONLY valid JSON with the same agent keys, containing the improved prompts."""

    try:
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT + "\n\nIMPORTANT: Return ONLY valid JSON. No markdown, no explanation, no code blocks."},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=4096,
        )

        content = response.choices[0].message.content or "{}"

        # Strip markdown code blocks if present
        content = content.strip()
        if content.startswith("```"):
            lines = content.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            content = "\n".join(lines)

        import json
        result = json.loads(content)

        for agent in AGENTS:
            if agent not in result or not result[agent]:
                result[agent] = template_prompts[agent]

        await client.close()
        return result

    except Exception as e:
        await client.close()
        return template_prompts


def generate_pure_llm_sync(
    user_description: str,
    api_key: str,
    base_url: str,
    model: str,
) -> dict[str, str]:
    client = AsyncOpenAI(api_key=api_key, base_url=base_url)

    system = """You are an expert AI CTO system prompt generator. Given a description of a software project, you generate highly specific system prompts for 8 specialized AI CTO agents.

The 8 agents are:
1. cto_orchestrator - Coordinates all agents, manages pipeline
2. cto_audit_analyzer - Parses audits, security, performance findings
3. cto_architect - Designs and reviews system architecture, APIs
4. cto_planner - Creates implementation plans, breaks down tasks
5. cto_executor - Generates code, implements features, fixes bugs
6. cto_tester - Writes tests, reviews code quality, analyzes test results
7. cto_monitor - Tracks progress, identifies bottlenecks, status reports
8. cto_documenter - Generates READMEs, API docs, architecture docs, code comments

Return ONLY valid JSON with these exact keys."""

    try:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            response = loop.run_until_complete(
                client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system},
                        {"role": "user", "content": f"Generate AI CTO agent prompts for this project:\n\n{user_description}"},
                    ],
                    temperature=0.3,
                    max_tokens=4096,
                    response_format={"type": "json_object"},
                )
            )
        finally:
            loop.close()

        content = response.choices[0].message.content or "{}"
        import json
        result = json.loads(content)

        for agent in AGENTS:
            if agent not in result:
                result[agent] = ""

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(client.close())
        finally:
            loop.close()

        return result

    except Exception as e:
        raise RuntimeError(f"Pure LLM generation failed: {e}")
